############################
#                          #
#      FWChatControl       #
#      by Tigierrei        #
#                          #
############################

#SETTINGS
#Max messages that a player can send every second. High values could allow players to flood the chat
maxMessagesPerSecond: 8
#Warn if the player is flooding. Flooding means sending more messages per seconds than the allowed ones
warnIfFlooding: false
#Percentage threshold after the which the message will be lower cased
maxCapsCharPercentage: 40
warnIfCapsing: false
#TRUE = the player will receive a warn point if he uses a banned word
warnIfUsingBannedWords: true
#TRUE = the first letter of every message will be capitalized
capitalizeFirstLetter: false
#After how many seconds the plugin should reduce by one the warn points of a player
reduceWarnPeriod: 86400
bannedWords:
  - "[s][t][r][o][n][z][o]"
#Avabilable punishments types: KICK, MUTE, BAN
#The duration is expressed in seconds (NOT milliseconds). Example: 1 hour = 3600 seconds
punishments:
  3:
    type: KICK
    duration: 0
  4:
    type: MUTE
    duration: 3600
  5:
    type: BAN
    duration: 3600