name: ChatController
version: 1.0.0
main: it.filippocavallari.chatcontroller.ChatController
api-version: 1.16
depend:
  - Essentials
softdepend:
  - TownyChat
commands:
  cc:
    aliases:
      - chatcontroller
    description: Root command of ChatController