name: FWChatControl
version: @version@
main: it.forgottenworld.fwchatcontrol.FWChatControl
api-version: 1.16
depend:
  - TownyChat
  - Essentials
commands:
  fwcc:
    aliases:
      - fwchatcontrol
      - chatcontrol
      - cc
    description: Admin command of FWChatControl